# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_distance_haversine <- function(latFrom, lonFrom, latTo, lonTo, tolerance) {
    .Call('_gtfs2gps_rcpp_distance_haversine', PACKAGE = 'gtfs2gps', latFrom, lonFrom, latTo, lonTo, tolerance)
}

